name: Next deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-next-js:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: npm install

      - name: Build app and export static html
        run: npm run build --if-present


  deploy-website:

    runs-on: ubuntu-latest

    steps:
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ae8be.netcup.net
          username: github-actions
          password: ${{ secrets.NETCUP_FTP }}
          local-dir: ./out/
          server-dir: /bachata-and-more.de/httpdocs/
