name: Next deployment

on:
  push:
    branches: [ "somabay-event" ]
  pull_request:
    branches: [ "somabay-event" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      
      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn build

      - name: Generate sitemap
        run: yarn postbuild

      - name: Export static files
        run: yarn export

      - name: 📂 Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ae8be.netcup.net
          username: github-actions
          password: ${{ secrets.NETCUP_FTP }}
          local-dir: ./out/
          server-dir: /somabay.bachata-and-more.de/httpdocs/